name: everyday-birthday

on:
  schedule:
    - cron: "1 15 * * *"
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: bun install
        run: bun install
      - name: disable Ubuntu's security feature 
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: run (retry at most 3 times including 1st try)
        run: bun index || (sleep 60 && bun index) || (sleep 60 && bun index)
        env:
          TWITTER_ID: ${{ secrets.TWITTER_ID }}
          YEAR: ${{ secrets.YEAR }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      - name: Setup a-know/pi
        uses: peaceiris/actions-pixela@v2
        with:
          pi_version: '1.2.0'
      - name: Increment
        env:
          PIXELA_USER_TOKEN: ${{ secrets.PIXELA_USER_TOKEN }}
        run: |
          pi pixel increment -u gecko655 -g birthdays
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: general
          SLACK_MESSAGE: Failed to make today as birthday
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
