name: everyday-birthday

on:
  schedule:
    - cron: "1 15 * * *"
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: run (retry at most 3 times including 1st try)
        run: npm run index || (sleep 60 && npm run index) || (sleep 60 && npm run index)
        env:
          TWITTER_ID: ${{ secrets.TWITTER_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          YEAR: ${{ secrets.YEAR }}
          MAIL: ${{ secrets.MAIL }}
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      - name: screenshot
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
