name: everyday-birthday

on:
  schedule:
    - cron: "1 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: run (retry at most 3 times including 1st try)
        run: npm run index || sleep 60; npm run index || sleep 60; npm run index
        env:
          TWITTER_ID: ${{ secrets.TWITTER_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          YEAR: ${{ secrets.YEAR }}
          MAIL: ${{ secrets.MAIL }}
